{% set name = "makim" %}
{% set version = "1.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/makim-{{ version }}.tar.gz
  sha256: c22c701bb1544975052f0d6e4a1f86c7ede349fea06c91b824f22f8074f10aae

build:
  entry_points:
    - makim = makim.__main__:run_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry >=1.5.1
    - pip
  run:
    - __unix
    - python >={{ python_min }},<4.0.0
    - sh >=2.0.0
    - pyyaml >=5.0
    - jinja2 >=2.0
    - xonsh >=0.14.0
    - python-dotenv >=0.21.1
    - typer >=0.9.0
    - fuzzywuzzy >=0.18.0
    - python-levenshtein >=0.23.0
    - rich >=13.7.0
    - shellingham >=1.5.4

test:
  files:
    - .makim.yaml
  imports:
    - makim
  commands:
    - pip check
    - makim --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/osl-incubator/makim
  summary: Simplify the usage of containers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felipepaes
    - xmnlab
    - abhijeetSaroha
